# Generated by Django 4.2.7 on 2023-12-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=70)),
                ('content', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=100)),
                ('timestamp', models.DateField(blank=True)),
            ],
        ),
    ]
