# Generated by Django 4.2.7 on 2023-12-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=70)),
                ('email', models.EmailField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=20)),
                ('contact', models.IntegerField(default=0)),
                ('timestamp', models.TimeField(auto_now_add=True)),
                ('message', models.TextField(default='', max_length=500)),
            ],
        ),
    ]
